Gabriel/home page rework
CMPUT301W24T01/noRAM pull request #104
Opened 2024-03-30 17:50 UTC by gdumouli

- Changed the main page design
- Random event is displayed (and clickable) on main page

2024-03-30 19:54 UTC, WhoShotCupidd commented on code/noRAM/app/src/main/java/com/example/noram/MainActivity.java
> +        eventLocation.setText(event.getLocation());
could we get a few more comments here please

2024-03-30 20:00 UTC, WhoShotCupidd requested changes
Check the one comment I made please. 

Could we also make the event on the homepage a bit more centered the home page feels slightly segmented between the top and the bottom 

Also, did you look into the carousel design for the events?

2024-03-30 20:37 UTC, gdumouli commented
> Check the one comment I made please.
> 
> Could we also make the event on the homepage a bit more centered the home page feels slightly segmented between the top and the bottom
> 
> Also, did you look into the carousel design for the events?

I don't think the carousel would be worthwhile: users don't stay on the main menu for very long and can use the event-list fragment if they want to scroll through available events. 
Was it for aesthetics that we wanted it?

2024-03-31 03:39 UTC, ColeDewis commented
> > Check the one comment I made please.
> > Could we also make the event on the homepage a bit more centered the home page feels slightly segmented between the top and the bottom
> > Also, did you look into the carousel design for the events?
> 
> I don't think the carousel would be worthwhile: users don't stay on the main menu for very long and can use the event-list fragment if they want to scroll through available events. Was it for aesthetics that we wanted it?

not christiaan but yeah, its mostly for aesthetics. it's not really intended to be a way to browse events, more just as a gallery of "here's some stuff happening soon" that gives the home screen some flair

2024-03-31 22:00 UTC, WhoShotCupidd commented
> > > Check the one comment I made please.
> > > Could we also make the event on the homepage a bit more centered the home page feels slightly segmented between the top and the bottom
> > > Also, did you look into the carousel design for the events?
> > 
> > 
> > I don't think the carousel would be worthwhile: users don't stay on the main menu for very long and can use the event-list fragment if they want to scroll through available events. Was it for aesthetics that we wanted it?
> 
> not christiaan but yeah, its mostly for aesthetics. it's not really intended to be a way to browse events, more just as a gallery of "here's some stuff happening soon" that gives the home screen some flair

yeah I think we should push this and we can look into the carousel later on

2024-04-01 02:03 UTC, WhoShotCupidd approved these changes
lgtm now

2024-04-01 15:39 UTC, merged